// Generated by gencpp from file bhand_controller/Actions.msg
// DO NOT EDIT!


#ifndef BHAND_CONTROLLER_MESSAGE_ACTIONS_H
#define BHAND_CONTROLLER_MESSAGE_ACTIONS_H

#include <ros/service_traits.h>


#include <bhand_controller/ActionsRequest.h>
#include <bhand_controller/ActionsResponse.h>


namespace bhand_controller
{

struct Actions
{

typedef ActionsRequest Request;
typedef ActionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Actions
} // namespace bhand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bhand_controller::Actions > {
  static const char* value()
  {
    return "89af4e368677e306adbb14bec6d3e1c0";
  }

  static const char* value(const ::bhand_controller::Actions&) { return value(); }
};

template<>
struct DataType< ::bhand_controller::Actions > {
  static const char* value()
  {
    return "bhand_controller/Actions";
  }

  static const char* value(const ::bhand_controller::Actions&) { return value(); }
};


// service_traits::MD5Sum< ::bhand_controller::ActionsRequest> should match 
// service_traits::MD5Sum< ::bhand_controller::Actions > 
template<>
struct MD5Sum< ::bhand_controller::ActionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bhand_controller::Actions >::value();
  }
  static const char* value(const ::bhand_controller::ActionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bhand_controller::ActionsRequest> should match 
// service_traits::DataType< ::bhand_controller::Actions > 
template<>
struct DataType< ::bhand_controller::ActionsRequest>
{
  static const char* value()
  {
    return DataType< ::bhand_controller::Actions >::value();
  }
  static const char* value(const ::bhand_controller::ActionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bhand_controller::ActionsResponse> should match 
// service_traits::MD5Sum< ::bhand_controller::Actions > 
template<>
struct MD5Sum< ::bhand_controller::ActionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bhand_controller::Actions >::value();
  }
  static const char* value(const ::bhand_controller::ActionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bhand_controller::ActionsResponse> should match 
// service_traits::DataType< ::bhand_controller::Actions > 
template<>
struct DataType< ::bhand_controller::ActionsResponse>
{
  static const char* value()
  {
    return DataType< ::bhand_controller::Actions >::value();
  }
  static const char* value(const ::bhand_controller::ActionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BHAND_CONTROLLER_MESSAGE_ACTIONS_H
