// Generated by gencpp from file bhand_controller/ActionsRequest.msg
// DO NOT EDIT!


#ifndef BHAND_CONTROLLER_MESSAGE_ACTIONSREQUEST_H
#define BHAND_CONTROLLER_MESSAGE_ACTIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bhand_controller
{
template <class ContainerAllocator>
struct ActionsRequest_
{
  typedef ActionsRequest_<ContainerAllocator> Type;

  ActionsRequest_()
    : action(0)  {
    }
  ActionsRequest_(const ContainerAllocator& _alloc)
    : action(0)  {
  (void)_alloc;
    }



   typedef int32_t _action_type;
  _action_type action;




  typedef boost::shared_ptr< ::bhand_controller::ActionsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bhand_controller::ActionsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActionsRequest_

typedef ::bhand_controller::ActionsRequest_<std::allocator<void> > ActionsRequest;

typedef boost::shared_ptr< ::bhand_controller::ActionsRequest > ActionsRequestPtr;
typedef boost::shared_ptr< ::bhand_controller::ActionsRequest const> ActionsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bhand_controller::ActionsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bhand_controller::ActionsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bhand_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'bhand_controller': ['/home/baxter/mn/src/barrett_hand/bhand_controller/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bhand_controller::ActionsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bhand_controller::ActionsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bhand_controller::ActionsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b028501ac85c840a01d50342b4cc9b6e";
  }

  static const char* value(const ::bhand_controller::ActionsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb028501ac85c840aULL;
  static const uint64_t static_value2 = 0x01d50342b4cc9b6eULL;
};

template<class ContainerAllocator>
struct DataType< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bhand_controller/ActionsRequest";
  }

  static const char* value(const ::bhand_controller::ActionsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 action\n\
";
  }

  static const char* value(const ::bhand_controller::ActionsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bhand_controller::ActionsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bhand_controller::ActionsRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BHAND_CONTROLLER_MESSAGE_ACTIONSREQUEST_H
