// Generated by gencpp from file bhand_controller/SetControlMode.msg
// DO NOT EDIT!


#ifndef BHAND_CONTROLLER_MESSAGE_SETCONTROLMODE_H
#define BHAND_CONTROLLER_MESSAGE_SETCONTROLMODE_H

#include <ros/service_traits.h>


#include <bhand_controller/SetControlModeRequest.h>
#include <bhand_controller/SetControlModeResponse.h>


namespace bhand_controller
{

struct SetControlMode
{

typedef SetControlModeRequest Request;
typedef SetControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlMode
} // namespace bhand_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bhand_controller::SetControlMode > {
  static const char* value()
  {
    return "b696448a6984c2e37a93990a5f048086";
  }

  static const char* value(const ::bhand_controller::SetControlMode&) { return value(); }
};

template<>
struct DataType< ::bhand_controller::SetControlMode > {
  static const char* value()
  {
    return "bhand_controller/SetControlMode";
  }

  static const char* value(const ::bhand_controller::SetControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::bhand_controller::SetControlModeRequest> should match 
// service_traits::MD5Sum< ::bhand_controller::SetControlMode > 
template<>
struct MD5Sum< ::bhand_controller::SetControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bhand_controller::SetControlMode >::value();
  }
  static const char* value(const ::bhand_controller::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bhand_controller::SetControlModeRequest> should match 
// service_traits::DataType< ::bhand_controller::SetControlMode > 
template<>
struct DataType< ::bhand_controller::SetControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::bhand_controller::SetControlMode >::value();
  }
  static const char* value(const ::bhand_controller::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bhand_controller::SetControlModeResponse> should match 
// service_traits::MD5Sum< ::bhand_controller::SetControlMode > 
template<>
struct MD5Sum< ::bhand_controller::SetControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bhand_controller::SetControlMode >::value();
  }
  static const char* value(const ::bhand_controller::SetControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bhand_controller::SetControlModeResponse> should match 
// service_traits::DataType< ::bhand_controller::SetControlMode > 
template<>
struct DataType< ::bhand_controller::SetControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::bhand_controller::SetControlMode >::value();
  }
  static const char* value(const ::bhand_controller::SetControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BHAND_CONTROLLER_MESSAGE_SETCONTROLMODE_H
