set(robotiq_3f_gripper_articulated_msgs_MESSAGE_FILES "/home/baxter/mn/src/robotiq/robotiq_3f_gripper_articulated_msgs/msg/Robotiq3FGripperRobotInput.msg;/home/baxter/mn/src/robotiq/robotiq_3f_gripper_articulated_msgs/msg/Robotiq3FGripperRobotOutput.msg")
set(robotiq_3f_gripper_articulated_msgs_SERVICE_FILES "")
